name: KoreanGutMAGs
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - seqkit
  - bowtie2
  - samtools
  - trimmomatic
  - porechop
  - filtlong
  - flye
  - spades
  - metawrap
  - prokka  # Prokka for genome annotation
  - eggnog-mapper  # EggNOG Mapper for functional annotation
  - operams  # OPERA-MS for hybrid assembly
  - biopython
  - gcc
  - openjdk  # Required for some tools like EggNOG Mapper
